templates:
  - id: standard-mod
    src: https://github.com/Gluck-House/7dtd-mod-template
    version: 0.1.0
    repos:
      - repo: Gluck-House/7dtdTimeLoop
        branch: main
        enabled: true
