templates:
- id: standard-mod
  src: https://github.com/Gluck-House/7dtd-mod-template
  ref: v1.1.2
  repos:
  - repo: Gluck-House/7dtd-timeloop
    branch: main
    enabled: true
  - repo: Gluck-House/7dtd-poi-storage-rescue
    branch: main
    enabled: true
