#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 4 ]; then
    echo "usage: update_managed_7dtd_repo.sh <repo> <base_branch> <app_id> <latest_build_id>" >&2
    exit 1
fi

repo="$1"
base_branch="$2"
target_app_id="$3"
latest_build_id="$4"

token="${MANAGED_REPOS_TOKEN:?MANAGED_REPOS_TOKEN is required}"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

update_branch="chore/7dtd-build-update"
version_file=".github/7dtd-version.env"
export GH_TOKEN="$token"

git clone "https://x-access-token:${token}@github.com/${repo}.git" "$work_dir/repo" >/dev/null 2>&1
git -C "$work_dir/repo" checkout "$base_branch" >/dev/null 2>&1

if [ ! -f "$work_dir/repo/$version_file" ]; then
    echo "Repository ${repo} does not contain $version_file" >&2
    exit 1
fi

git -C "$work_dir/repo" config user.name "github-actions[bot]"
git -C "$work_dir/repo" config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# shellcheck disable=SC1090
source "$work_dir/repo/$version_file"

repo_app_id="${APP_ID:-}"
pinned_build_id="${BUILD_ID:-}"

if [ -z "$repo_app_id" ] || [ -z "$pinned_build_id" ]; then
    echo "Repository ${repo} contains an invalid $version_file" >&2
    exit 1
fi

if [ "$repo_app_id" != "$target_app_id" ]; then
    echo "Repository ${repo} pins APP_ID=${repo_app_id}, expected ${target_app_id}" >&2
    exit 1
fi

close_stale_pr() {
    local existing_pr_number
    existing_pr_number="$(
        gh pr list \
            --repo "$repo" \
            --state open \
            --head "$update_branch" \
            --json number \
            --jq '.[0].number // ""'
    )"

    if [ -n "$existing_pr_number" ]; then
        gh pr comment "$existing_pr_number" --repo "$repo" --body "Pinned 7 Days to Die build is already current. Closing automated update PR." >/dev/null
        gh pr close "$existing_pr_number" --repo "$repo" >/dev/null
    fi

    if git -C "$work_dir/repo" ls-remote --exit-code --heads origin "$update_branch" >/dev/null 2>&1; then
        git -C "$work_dir/repo" push origin ":refs/heads/${update_branch}" >/dev/null
    fi
}

if [ "$pinned_build_id" = "$latest_build_id" ]; then
    echo "Pinned build is already current for ${repo}"
    close_stale_pr
    exit 0
fi

tmpfile="$(mktemp)"
awk -v build_id="$latest_build_id" '
    BEGIN {
      updated = 0
    }
    /^BUILD_ID=/ {
      print "BUILD_ID=" build_id
      updated = 1
      next
    }
    {
      print
    }
    END {
      if (!updated) {
        exit 1
      }
    }
' "$work_dir/repo/$version_file" > "$tmpfile"
mv "$tmpfile" "$work_dir/repo/$version_file"

git -C "$work_dir/repo" add "$version_file"
if git -C "$work_dir/repo" diff --cached --quiet -- "$version_file"; then
    echo "No version-file diff produced for ${repo}"
    exit 0
fi

commit_message="chore(7dtd): bump pinned build id to ${latest_build_id}"
pr_title="$commit_message"
pr_body=$(
    cat <<EOF
Automated update of the pinned 7 Days to Die build metadata.

- App ID: \`${repo_app_id}\`
- Previous build ID: \`${pinned_build_id}\`
- Latest build ID: \`${latest_build_id}\`

This change was generated by \`7dtd-mod-infra\`, and the matching dependency bundle is available in shared S3 storage.
EOF
)

git -C "$work_dir/repo" checkout -B "$update_branch" >/dev/null 2>&1
git -C "$work_dir/repo" commit -m "$commit_message" >/dev/null
git -C "$work_dir/repo" push --force-with-lease origin "$update_branch" >/dev/null

existing_pr_number="$(
    gh pr list \
        --repo "$repo" \
        --state open \
        --head "$update_branch" \
        --json number \
        --jq '.[0].number // ""'
)"

if [ -n "$existing_pr_number" ]; then
    gh pr edit "$existing_pr_number" --repo "$repo" --title "$pr_title" --body "$pr_body" >/dev/null
    gh pr edit "$existing_pr_number" --repo "$repo" --add-label chore --add-label dependencies >/dev/null 2>&1 || true
else
    gh pr create \
        --repo "$repo" \
        --base "$base_branch" \
        --head "$update_branch" \
        --title "$pr_title" \
        --body "$pr_body" >/dev/null
    created_pr_number="$(
        gh pr list \
            --repo "$repo" \
            --state open \
            --head "$update_branch" \
            --json number \
            --jq '.[0].number // ""'
    )"
    if [ -n "$created_pr_number" ]; then
        gh pr edit "$created_pr_number" --repo "$repo" --add-label chore --add-label dependencies >/dev/null 2>&1 || true
    fi
fi

echo "Created or updated 7DTD build PR for ${repo}"
