name: reusable-pr-title

on:
  workflow_call:
    inputs:
      runner_label:
        required: false
        type: string
        default: ubuntu-latest

permissions:
  pull-requests: read

concurrency:
  group: reusable-pr-title-${{ github.repository }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  conventional-title:
    runs-on: ${{ inputs.runner_label }}
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          requireScope: false
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          validateSingleCommit: false
